### PR TITLE
Fix for pipeline id

### PR DESCRIPTION
**Pull request by Sosutha**
* Removed pipeline id from template for tc backend
* Removed pipeline id from introspection.json for tc backend

https://github.com/p4tc-dev/p4tc-e2e/issues/49

### CODE REVIEW

**Comment by vbnogueira** [comment]
I think the PR is missing the addition of the global variable of type `struct p4tc_filter_fields` described here (https://github.com/p4tc-dev/p4tc-e2e/issues/49#issuecomment-1946963510).
Also the control blocks eBPF program should use that global variable to determine the pipeline ID.
So instead of hardcoding `1` as in here: https://github.com/Sosutha/p4c/blob/p4tc_pipeline_id_fix/testdata/p4tc_samples_outputs/calculator_control_blocks.c#L68

The program should do something like this:

```
struct p4tc_table_entry_act_bpf_params__local params = {
     .pipeid = p4tc_filter_fields.pipeid,
     .tblid = 1
};
```

**Comment by Sosutha** [comment]
@vbnogueira . This PR is still in progress. Implementation is not yet completed. Once completed, I will let you know for your review

**Comment by Sosutha** [comment]
@vbnogueira Please review now

**Comment by vbnogueira** [comment]
> @vbnogueira Please review now

@Sosutha LGTM

**Review by psivanup — APPROVED** [review]
The changes look fine to me

**Review by usha1830 — APPROVED** [review]
LGTM.

**Pull request closed without merging**
